-- Add more venues across UAE regions to reach 100+ venues
INSERT INTO public.venues (name, type, region, city, address) VALUES
-- More Dubai Venues
('Iris Dubai', 'bar', 'Dubai', 'Dubai', 'The Oberoi Dubai'),
('Q43', 'bar', 'Dubai', 'Dubai', 'Media One Hotel'),
('Siddharta Lounge', 'bar', 'Dubai', 'Dubai', 'Grosvenor House'),
('Jetty Lounge', 'bar', 'Dubai', 'Dubai', 'One&Only Royal Mirage'),
('101 Lounge & Bar', 'bar', 'Dubai', 'Dubai', 'One&Only The Palm'),
('Lock Stock & Barrel', 'bar', 'Dubai', 'Dubai', 'JBR The Walk'),
('McGettigan''s', 'bar', 'Dubai', 'Dubai', 'JLT'),
('The Irish Village', 'bar', 'Dubai', 'Dubai', 'Garhoud'),
('BiCE Mare', 'restaurant', 'Dubai', 'Dubai', 'Souk Al Bahar'),
('Armani/Ristorante', 'restaurant', 'Dubai', 'Dubai', 'Armani Hotel'),
('Hakkasan', 'restaurant', 'Dubai', 'Dubai', 'Atlantis The Palm'),
('Ossiano', 'restaurant', 'Dubai', 'Dubai', 'Atlantis The Palm'),
('Nathan Outlaw at Al Mahara', 'restaurant', 'Dubai', 'Dubai', 'Burj Al Arab'),
('Pierchic', 'restaurant', 'Dubai', 'Dubai', 'Al Qasr Madinat Jumeirah'),
('Tresind Studio', 'restaurant', 'Dubai', 'Dubai', 'Al Quoz'),
('STAY by Yannick Alléno', 'restaurant', 'Dubai', 'Dubai', 'One&Only The Palm'),
('Thiptara', 'restaurant', 'Dubai', 'Dubai', 'Palace Downtown'),
('Dinner by Heston Blumenthal', 'restaurant', 'Dubai', 'Dubai', 'Atlantis The Royal'),
('Hoseki', 'restaurant', 'Dubai', 'Dubai', 'Bulgari Resort'),
('Il Ristorante - Niko Romito', 'restaurant', 'Dubai', 'Dubai', 'Bulgari Resort'),
('COYA Dubai', 'restaurant', 'Dubai', 'Dubai', 'Four Seasons DIFC'),
('Goldfish', 'restaurant', 'Dubai', 'Dubai', 'Atlantis The Palm'),
('SeaFu', 'restaurant', 'Dubai', 'Dubai', 'Atlantis The Palm'),
('Bread Street Kitchen', 'restaurant', 'Dubai', 'Dubai', 'Atlantis The Palm'),
('Roka', 'restaurant', 'Dubai', 'Dubai', 'DIFC'),
('The MAINE Oyster Bar', 'restaurant', 'Dubai', 'Dubai', 'DIFC'),
('Roberto''s', 'restaurant', 'Dubai', 'Dubai', 'DIFC'),
('La Serre Bistro', 'restaurant', 'Dubai', 'Dubai', 'Downtown'),
('Carnival by Tresind', 'restaurant', 'Dubai', 'Dubai', 'Bluewaters Island'),
('Maiden Shanghai', 'restaurant', 'Dubai', 'Dubai', 'Meydan'),

-- Abu Dhabi Venues
('Ray''s Bar', 'bar', 'Abu Dhabi', 'Abu Dhabi', 'Jumeirah at Etihad Towers'),
('Jazz Bar & Dining', 'bar', 'Abu Dhabi', 'Abu Dhabi', 'Hilton Abu Dhabi'),
('Stratos', 'bar', 'Abu Dhabi', 'Abu Dhabi', 'Le Royal Meridien'),
('Cooper''s Bar & Restaurant', 'bar', 'Abu Dhabi', 'Abu Dhabi', 'Park Rotana'),
('P.J. O''Reilly''s', 'bar', 'Abu Dhabi', 'Abu Dhabi', 'Le Royal Meridien'),
('Captain''s Arms', 'bar', 'Abu Dhabi', 'Abu Dhabi', 'Le Meridien'),
('MAD on Yas Island', 'nightclub', 'Abu Dhabi', 'Abu Dhabi', 'Yas Island'),
('Iris Yas Island', 'bar', 'Abu Dhabi', 'Abu Dhabi', 'Yas Island'),
('Catch', 'restaurant', 'Abu Dhabi', 'Abu Dhabi', 'Rosewood Abu Dhabi'),
('Li Beirut', 'restaurant', 'Abu Dhabi', 'Abu Dhabi', 'Jumeirah at Etihad Towers'),
('Hakkasan Abu Dhabi', 'restaurant', 'Abu Dhabi', 'Abu Dhabi', 'Emirates Palace'),
('Pearls & Caviar', 'restaurant', 'Abu Dhabi', 'Abu Dhabi', 'Jumeirah at Etihad Towers'),
('Mijana', 'restaurant', 'Abu Dhabi', 'Abu Dhabi', 'Emirates Palace'),
('Coya Abu Dhabi', 'restaurant', 'Abu Dhabi', 'Abu Dhabi', 'The Galleria Al Maryah Island'),
('Roberto''s Abu Dhabi', 'restaurant', 'Abu Dhabi', 'Abu Dhabi', 'EDITION Abu Dhabi'),
('LPM Restaurant & Bar', 'restaurant', 'Abu Dhabi', 'Abu Dhabi', 'The Galleria'),
('Zuma Abu Dhabi', 'restaurant', 'Abu Dhabi', 'Abu Dhabi', 'The Galleria'),
('99 Sushi Bar', 'restaurant', 'Abu Dhabi', 'Abu Dhabi', 'The Galleria'),
('Quest', 'restaurant', 'Abu Dhabi', 'Abu Dhabi', 'W Abu Dhabi'),
('Nusr-Et Abu Dhabi', 'restaurant', 'Abu Dhabi', 'Abu Dhabi', 'The Galleria'),

-- Sharjah Venues
('The Brewery', 'bar', 'Sharjah', 'Sharjah', 'Radisson Blu Sharjah'),
('Cook & Room', 'restaurant', 'Sharjah', 'Sharjah', 'Sheraton Sharjah'),
('Arjwan', 'restaurant', 'Sharjah', 'Sharjah', 'Sheraton Sharjah'),
('Buhara', 'restaurant', 'Sharjah', 'Sharjah', 'Radisson Blu Sharjah'),
('Al Qasba', 'restaurant', 'Sharjah', 'Sharjah', 'Al Qasba'),

-- Ras Al Khaimah Venues
('Bassata Beach Bar', 'bar', 'Ras Al Khaimah', 'Ras Al Khaimah', 'DoubleTree by Hilton RAK'),
('The Anchor Bar', 'bar', 'Ras Al Khaimah', 'Ras Al Khaimah', 'Waldorf Astoria RAK'),
('Lexington Grill', 'restaurant', 'Ras Al Khaimah', 'Ras Al Khaimah', 'Waldorf Astoria RAK'),
('Marjan', 'restaurant', 'Ras Al Khaimah', 'Ras Al Khaimah', 'Waldorf Astoria RAK'),
('UMI', 'restaurant', 'Ras Al Khaimah', 'Ras Al Khaimah', 'Waldorf Astoria RAK'),

-- Ajman Venues
('Breeze Beach Bar', 'bar', 'Ajman', 'Ajman', 'Ajman Saray'),
('Cafe Arabesque', 'restaurant', 'Ajman', 'Ajman', 'Ajman Saray'),
('Bukhara', 'restaurant', 'Ajman', 'Ajman', 'Fairmont Ajman'),

-- Al Ain Venues
('Belgian Cafe', 'bar', 'Al Ain', 'Al Ain', 'Danat Al Ain Resort'),
('Paco''s', 'restaurant', 'Al Ain', 'Al Ain', 'Radisson Blu Al Ain'),
('Min Zaman', 'restaurant', 'Al Ain', 'Al Ain', 'Al Ain Rotana'),

-- More Dubai Premium Venues
('Le Petite Maison', 'restaurant', 'Dubai', 'Dubai', 'DIFC'),
('Scalini', 'restaurant', 'Dubai', 'Dubai', 'Four Seasons Jumeirah'),
('The Lighthouse', 'restaurant', 'Dubai', 'Dubai', 'The Dubai Edition'),
('Market Kitchen', 'restaurant', 'Dubai', 'Dubai', 'Vida Downtown'),
('Ninive', 'restaurant', 'Dubai', 'Dubai', 'Jumeirah Emirates Towers'),
('Al Nafoorah', 'restaurant', 'Dubai', 'Dubai', 'Jumeirah Emirates Towers'),
('Splendido', 'restaurant', 'Dubai', 'Dubai', 'The Ritz-Carlton DIFC'),
('La Serre', 'restaurant', 'Dubai', 'Dubai', 'Downtown'),
('Zaroob', 'restaurant', 'Dubai', 'Dubai', 'Multiple Locations'),
('Social House', 'restaurant', 'Dubai', 'Dubai', 'The Dubai Mall'),
('Public', 'restaurant', 'Dubai', 'Dubai', 'City Walk'),
('Publique', 'restaurant', 'Dubai', 'Dubai', 'Gate District'),
('BB Social Dining', 'restaurant', 'Dubai', 'Dubai', 'DIFC'),
('Twiggy by La Cantine', 'restaurant', 'Dubai', 'Dubai', 'City Walk'),
('Couqley French Bistro', 'restaurant', 'Dubai', 'Dubai', 'Souk Al Bahar'),
('Reform Social & Grill', 'restaurant', 'Dubai', 'Dubai', 'The Lakes'),
('Folly', 'restaurant', 'Dubai', 'Dubai', 'Madinat Jumeirah'),
('Shimmers', 'restaurant', 'Dubai', 'Dubai', 'Madinat Jumeirah'),
('Pai Thai', 'restaurant', 'Dubai', 'Dubai', 'Madinat Jumeirah'),
('Zheng He''s', 'restaurant', 'Dubai', 'Dubai', 'Madinat Jumeirah'),
('Rang Mahal', 'restaurant', 'Dubai', 'Dubai', 'JW Marriott Marquis'),
('Tong Thai', 'restaurant', 'Dubai', 'Dubai', 'Asateer Tent Atlantis'),
('The Farm', 'restaurant', 'Dubai', 'Dubai', 'Al Barari');
